<a href="https://colab.research.google.com/github/parthava-adabala/learning/blob/main/00PyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.__version__

'2.8.0+cu126'

In [3]:
!nvidia-smi

Fri Oct 17 17:22:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
torch.cuda.is_available()

True

#Tensors

In [5]:
scalar = torch.tensor(7)
print(scalar.ndim)
print(type(scalar))
print(type(scalar.item()))

0
<class 'torch.Tensor'>
<class 'int'>


In [6]:
vector =  torch.tensor([83,43])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [7]:
MATRIX = torch.tensor([[1,2,3],[3,4,5]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 3])


In [8]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


##Random Tensors

In [9]:
random_tensor = torch.rand(3,4)
print(random_tensor.ndim)
print(random_tensor.shape)
random_tensor

2
torch.Size([3, 4])


tensor([[0.1814, 0.7982, 0.0269, 0.0101],
        [0.5097, 0.9056, 0.8697, 0.9665],
        [0.5093, 0.3078, 0.8519, 0.9942]])

In [10]:
random_image_tensor = torch.rand(size=(3,224,224))
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([3, 224, 224]))

###Zeroes and Ones

In [11]:
zeros =  torch.zeros(3,4)
ones = torch.ones(3,4)
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [12]:
ones.dtype

torch.float32

In [13]:
torch.tensor([1,2,3], dtype=torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

#Range tensors

In [14]:
one_to_ten = torch.arange(0,10)
one_to_ten_step_2 = torch.arange(0,10,2)
one_to_ten, one_to_ten_step_2

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 2, 4, 6, 8]))

In [15]:
five_zeros = torch.zeros_like(one_to_ten_step_2, dtype=torch.float16)
five_zeros

tensor([0., 0., 0., 0., 0.], dtype=torch.float16)

# Tensor datatypes

In [16]:
example_tensor = torch.tensor([1,2,3], dtype=None, device="cuda", requires_grad=False)
example_tensor, example_tensor.dtype

(tensor([1, 2, 3], device='cuda:0'), torch.int64)

In [17]:
float_16_tensor = example_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16), torch.float16)

In [18]:
float_16_tensor.dtype, float_16_tensor.device, float_16_tensor.requires_grad

(torch.float16, device(type='cuda', index=0), False)

In [19]:
float_16_tensor.size(), float_16_tensor.shape

(torch.Size([3]), torch.Size([3]))

##Manipulating tensors

In [20]:
tensor = torch.tensor([1,2,3])
tensor + 10, tensor*10, tensor

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([1, 2, 3]))

In [21]:
torch.mul(tensor,10), torch.add(tensor,10), torch.sub(tensor,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([-9, -8, -7]))

In [22]:
tensor * tensor

tensor([1, 4, 9])

In [23]:
%%time
torch.matmul(tensor,tensor), tensor @ tensor

CPU times: user 1.02 ms, sys: 2 µs, total: 1.02 ms
Wall time: 10.2 ms


(tensor(14), tensor(14))

In [24]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)), torch.mm(torch.rand(3,2), torch.rand(2,3))

(tensor([[0.1735, 0.2373, 0.0794],
         [0.1651, 0.5401, 0.5104],
         [0.2631, 0.4079, 0.1868]]),
 tensor([[0.3334, 0.5182, 0.9155],
         [0.1544, 0.3233, 0.5977],
         [0.1111, 0.2539, 0.4745]]))

In [25]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
torch.mm(tensor_A, tensor_A.T) # transpose

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

#Min Max Mean

In [26]:
tensor_A.min(), tensor_A.max(), tensor_A.type(torch.float32).mean()

(tensor(1), tensor(6), tensor(3.5000))

In [27]:
torch.min(tensor_A), torch.max(tensor_A), torch.mean(tensor_A.type(torch.float32))

(tensor(1), tensor(6), tensor(3.5000))

In [30]:
tensor_A.argmax(), tensor_A.argmin()

(tensor(5), tensor(0))

#Reshaping, Stacking , Squeezing

In [32]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [37]:
z = x.view(1,9) # Changinz z changes x.
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [35]:
torch.vstack([x,x,x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [39]:
torch.stack([x,x,x], dim=1), torch.stack([x,x,x], dim=0)

(tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [44]:
x = torch.rand(1,1,1,10)
x, x.shape, x.squeeze(), x.squeeze().shape

(tensor([[[[0.0645, 0.5504, 0.1388, 0.5686, 0.2324, 0.4791, 0.3479, 0.0597,
            0.0096, 0.1886]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.0645, 0.5504, 0.1388, 0.5686, 0.2324, 0.4791, 0.3479, 0.0597, 0.0096,
         0.1886]),
 torch.Size([10]))

In [45]:
x.unsqueeze(dim=0), x.unsqueeze(dim=0).shape

(tensor([[[[[0.0645, 0.5504, 0.1388, 0.5686, 0.2324, 0.4791, 0.3479, 0.0597,
             0.0096, 0.1886]]]]]),
 torch.Size([1, 1, 1, 1, 10]))

In [46]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

#Indexing with pytorch is same as indexing with NumPy

#pytorch and numpy

In [48]:
import torch
import numpy as np

array = np.arange(1.,10.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [49]:
tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

#Reproducibility

In [50]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3907, 0.1041, 0.1416, 0.1682],
        [0.8760, 0.3386, 0.6524, 0.9450],
        [0.3844, 0.3365, 0.4149, 0.9070]])
tensor([[0.9853, 0.5319, 0.0271, 0.0266],
        [0.3865, 0.4514, 0.4385, 0.1285],
        [0.7501, 0.5345, 0.2110, 0.9463]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [52]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#GPU and device agnostic code

In [53]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [54]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [59]:
tensor_on_gpu = tensor.to(device)

In [60]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [61]:
tensor_on_gpu.to("cpu").device

device(type='cpu')